export PATH=$PATH:/home/wojtek/Bin
export LC_ALL="en_US.UTF-8"
export PRINTER=J4120DW
export EDITOR=vim
export DMENU_STD_THEME=
export LESSHISTFILE=-
export XDG_CONFIG_HOME=/home/wojtek/.config
export XDG_CACHE_HOME=/home/wojtek/.cache
export XDG_DATA_HOME=/home/wojtek/.local/share
export XDG_DATA_DIRS=/usr/local/share:/usr/share
export XDG_CONFIG_DIRS=/etc/xdg
export XDG_TEMPLATES_DIR=/home/wojtek/Templates
export XDG_VIDEOS_DIR=/home/wojtek/Video
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc
export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
