#!/bin/sh
DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${1:-10}"

df -h -P -l "$DIR" | awk -v alert_low=$ALERT_LOW '
/\/.*/ {
  # full text
  print $5

  # short text
  print $5

  use=$5

  # no need to continue parsing
  exit 0
}

END {
  gsub(/%$/,"",use)
  #color
  if (100 - use < alert_low)
    print "#FF0000"
}
'
