#!/bin/sh
case $BLOCK_BUTTON in
  1) /usr/bin/urxvt -e newsboat > /dev/null;;
esac

while pgrep newsboat > /dev/null; do
    sleep 1
done

full_text="$(newsboat -x print-unread | awk '{print $1}')"

echo "$full_text";
exit 0
