export PATH=$PATH:/home/wojtek/Bin
export LC_ALL="en_US.UTF-8"
export PRINTER=J4120DW
export EDITOR=vim
export DMENU_STD_THEME=
export LESSHISTFILE=/dev/null
export XDG_CONFIG_HOME=/home/wojtek/.config
source ~/.bashrc
export QT_QPA_PLATFORMTHEME=gtk2
