#!/bin/sh

acpi -b | awk '{
		sub(/,/, "", $4)
		sub(/%/, "", $4)
		sub(/,/, "", $3)

		value = int($4)
		state = $3
		if (state == "Charging") { symbol = "" }
		else
		{
			if      (value > 75) { symbol = "" }
			else if (value > 50) { symbol = "" }
			else if (value > 25) { symbol = "" }
			else if (value > 5)  { symbol = "" }
			else                 { symbol = "" }
		}

		print symbol" "value"%"
		if(NR==1)
			print " "
	}' | tr '\n' ' ' && echo
